sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: dngfFmjafyzsVwYpPqt/XeXl7ZSUZ+AKCdfx7guQikyBP4byCpJayQG5pBlUc6fuMka0goK/wKq3fyiDD+f2wBoczPxgdz1xdvdc9Gx6uBHIVCIi8iFSaUuUmzjNCQ1B4BBdYWglLuWzq6ss24bblNEnmgFeOvWpTvKfk4Yx8IqKHVbn25xMs1Alm/MdQW86EPbmGbxaC/1pMhpWcRhdDAoY9hNPeN011NzUtTRY96ilxhj56CKP3qvV+L5xshe4nIpkm0mPtVJ+YegJrAjbQqaChAlcMmC+QavzbPS3DeE/qVNSs+4pYRz7WmtH/wbM7btrucU8wX7mIdvCUs655gRhUmK2yzkK4dAehFjoRl9IScTWjmGaEuI+lUr1te37qWhTORyLuUA3t6ui9aXblhYJz6dyo7pFfGaLcVFqpij94M1k5b/2t661YC/X4x0lB9q47E9biQJPhNuzUsHBy6JmB8UAb6hfIXkfd40UryGJ/KJHJ/pKDS7HkC4aIhcBHMUzxG6oMY3ksPwxRwZXxOybHlTSVXA7hYqUxunj9QviqKVNOnEcJsVNEz/TdSwbGLZpH1CngQtCkUkE4inSHBENGXIcmGUTQIFhHFrG+W2WgDAtIlMqU3pPEbv3v1hRnv9sooK0JXlWky7ft7JkGS4Z432KJ08irCTrFMFWM5s=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Mutter-und-Kind--Ein-Gedicht-in-sieben-Ges-ngen_4083
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy